name: JS Testing

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: 16.x
        
    - name: Setup Chromium
      uses: browser-actions/setup-chrome@latest
    - name: Install using Lerna
      run: |
        npm i -g patch-package
        yarn install
        yarn run lerna bootstrap
        
    - name: Build Starboard Rich Editor
      working-directory: packages/starboard-rich-editor
      run: |
        yarn install
        yarn run build

    - name: Build Starboard Python
      working-directory: packages/starboard-python
      run: |
        yarn install
        yarn run build

    - name: Build
      working-directory: packages/starboard-notebook
      run: |
        yarn install
        yarn run build:nominify
        tar -czvf starboard-notebook.tar.gz dist/*
    
    - name: Upload built starboard-notebook.tar.gz as Github artifact
      uses: actions/upload-artifact@v4
      with:
        name: starboard-notebook.tar.gz
        path: packages/starboard-notebook/starboard-notebook.tar.gz
        retention-days: 10
    
    - name: Remove artifact from working directory
      working-directory: packages/starboard-notebook
      run: |
        rm starboard-notebook.tar.gz
    
    - name: Test
      working-directory: packages/starboard-notebook
      run: yarn test

    - name: Lint
      working-directory: packages/starboard-notebook
      run: npm run lint
      
    - name: Postinstall Starlit
      working-directory: packages/starboard-notebook/node_modules/starlit
      run: npm run postinstall
      
    - name: Starlit NBTest
      working-directory: packages/starboard-notebook
      run: npm run nbtest -- --timeout 150

