name: Publish alp-starboard-notebook to GitHub Packages

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "16.16.x"
          registry-url: "https://npm.pkg.github.com"
          scope: "@alp-os"
      - name: Build Starboard files
        run: npm run build
      - name: Publish alp-starboard-notebook
        run: cd packages/starboard-notebook && npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
